  
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;

namespace TestingDotNetPortability
{
   public partial class Student
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public Student()
      {
         Init();
      }

      // Persistent properties

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      public int Id { get; set; }

      public string Name { get; set; }

   }
}

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;

namespace TestingDotNetPortability
{
   public partial class Course
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public Course()
      {
         Init();
      }

      // Persistent properties

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      public int Id { get; set; }

      public string Course { get; set; }

   }
}

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;

namespace TestingDotNetPortability
{
   public partial class Enrollment
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public Enrollment()
      {
         Init();
      }

      // Persistent properties

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      public int Id { get; set; }

   }
}

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TestingDotNetPortability
{
   public partial class MyModel : Microsoft.EntityFrameworkCore.DbContext
   {
